# Generated by Django 5.1.6 on 2025-02-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaloupe',
            fields=[
                ('id_chaloupe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('nb_membre', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('jour', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.AutoField(primary_key=True, serialize=False)),
                ('place_disponible', models.IntegerField()),
                ('date_evenement', models.DateTimeField()),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societaire',
            fields=[
                ('id_societaire', models.AutoField(primary_key=True, serialize=False)),
                ('produit', models.CharField(max_length=50)),
                ('organisation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('civilite', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('code_postal', models.CharField(blank=True, max_length=6, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('complement_adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('premiere_connexion', models.DateTimeField(blank=True, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartSocial',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('date_achat', models.DateTimeField()),
                ('quantite', models.SmallIntegerField()),
                ('num_facture', models.CharField(max_length=50)),
                ('id_societaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.societaire')),
            ],
        ),
        migrations.AddField(
            model_name='societaire',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
        migrations.CreateModel(
            name='Rejoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirige', models.BooleanField()),
                ('id_chaloupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chaloupe')),
                ('id_societaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.societaire')),
            ],
            options={
                'unique_together': {('id_societaire', 'id_chaloupe')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connexion')),
                ('id_societaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.societaire')),
            ],
            options={
                'unique_together': {('id_societaire', 'jour')},
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_place', models.SmallIntegerField()),
                ('id_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evenement')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_evenement')},
            },
        ),
    ]
