# Generated by Django 5.1.6 on 2025-02-17 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaloupe',
            name='nb_membre',
        ),
    ]
