# Generated by Django 5.1.6 on 2025-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_utilisateur_code_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id_client_welogin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
