# Generated by Django 5.1.6 on 2025-02-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_utilisateur_is_active_utilisateur_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='mot_de_passe',
        ),
    ]
