# Generated by Django 5.1.6 on 2025-02-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_utilisateur_mot_de_passe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societaire',
            name='produit',
        ),
    ]
